DROP TABLE DECK;
DROP TABLE COLLECTION;
DROP TABLE USERS;
DROP TABLE LIBRARY;

SHOW TABLES;

LOAD DATA LOCAL INFILE 'users.txt' INTO TABLE USERS;
LOAD DATA LOCAL INFILE 'samplelibrary.txt' INTO TABLE LIBRARY;
LOAD DATA LOCAL INFILE 'collection.txt' INTO TABLE COLLECTION1;
LOAD DATA LOCAL INFILE 'deck.txt' INTO TABLE DECK;
#LOAD DATA LOCAL INFILE 'collection_link.txt' INTO TABLE COLLECTION_LINK;
