SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS LIBRARY;
 CREATE TABLE IF NOT EXISTS LIBRARY
(
LIBRARY_ID int NOT NULL,
Card_Name varchar(255) NOT NULL,
Ability varchar(255) NOT NULL,
Type_ varchar(255) NOT NULL,
Cost varchar(255) NOT NULL,
Primary Key(LIBRARY_ID)
);


DROP TABLE IF  EXISTS USERS;
 CREATE TABLE IF NOT EXISTS USERS
(
USER_ID int NOT NULL AUTO_INCREMENT ,
Username varchar(255) NOT NULL,
Password varchar(255) NOT NULL,
Primary Key(USER_ID)
);


DROP TABLE IF  EXISTS COLLECTION1;
CREATE TABLE IF NOT EXISTS COLLECTION1
(
ENTRY INT NOT NULL AUTO_INCREMENT,
LIBRARY_ID int NOT NULL ,
USER_ID int NOT NULL,
PRIMARY KEY(ENTRY),
Foreign Key(LIBRARY_ID) references LIBRARY(LIBRARY_ID),
Foreign Key(USER_ID) references USERS(USER_ID)
);
DROP TABLE IF  EXISTS DECK;
 CREATE TABLE IF NOT EXISTS DECK
(
DECK_ID int NOT NULL,
USER_ID int NOT NULL,
COLLECTION_ID INT NOT NULL,
#LIBRARY_CARD int NOT NULL,
PRIMARY KEY(DECK_ID),
FOREIGN KEY(COLLECTION_ID) REFERENCES COLLECTION1(LIBRARY_ID),
Foreign Key(USER_ID) references USERS(USER_ID)
#Foreign Key(LIBRARY_CARD) references LIBRARY(LIBRARY_ID)
);
SET FOREIGN_KEY_CHECKS=1;